export const SET_UMBRACOCONTENT = 'SET_UMBRACOCONTENT';
export const FETCH_UMBRACOCONTENT_FAILED = 'FETCH_UMBRACOCONTENT_FAILED';

export const REQUEST_PAGE_REQUEST = 'REQUEST_PAGE_REQUEST';
export const SET_REQUEST_PAGE_MODELS = 'SET_REQUEST_PAGE_MODELS';
export const FETCH_REQUEST_PAGE_FAILED = 'FETCH_REQUEST_PAGE_FAILED';



export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_PROFILE_IMAGE = 'SET_USER_PROFILE_IMAGE';
export const SET_SITE_SETTINGS = 'SET_SITE_SETTINGS';
